controller_joint_names: ['torso_joint_b1','torso_joint_b2','arm_left_joint_1_s','arm_left_joint_2_l',
'arm_left_joint_3_e','arm_left_joint_4_u','arm_left_joint_5_r','arm_left_joint_6_b','arm_left_joint_7_t',
'arm_right_joint_1_s','arm_right_joint_2_l','arm_right_joint_3_e','arm_right_joint_4_u','arm_right_joint_5_r',
'arm_right_joint_6_b','arm_right_joint_7_t','right_gripper_finger_joint','right_gripper_left_inner_knuckle_joint',
'right_gripper_left_inner_finger_joint','right_gripper_right_outer_knuckle_joint','right_gripper_right_inner_knuckle_joint',
'right_gripper_right_inner_finger_joint','arm_left_right_driver_joint','arm_left_right_follower_joint',
'arm_left_right_spring_link_joint','arm_left_left_driver_joint','arm_left_left_follower_joint','arm_left_left_spring_link_joint']
