base_link: 'base_link'

# =====================================================
left_hand:
    end_effector_name: 'left_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['left_gripper_to_robot_joint','arm_left_gripper_flange_joint','arm_left_gripper_force_sensor_joint',        'arm_left_gripper_coupling_joint','arm_left_link_robotiq_coupling_arm_left_base_joint',       'arm_left_left_driver_joint','arm_left_left_coupler_joint','arm_left_left_follower_joint',      'arm_left_left_pad_joint','arm_left_left_spring_link_joint','arm_left_right_driver_joint',      'arm_left_right_coupler_joint','arm_left_right_follower_joint','arm_left_right_pad_joint',     'arm_left_right_spring_link_joint']

    #open position
    pregrasp_posture : [0.0,0.0,0.0]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [1,1]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [0, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 0, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'arm_left_link_tcp"'
# =====================================================
right_hand:
    end_effector_name: 'right_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['right_gripper_to_robot_joint','right_gripper_gripper_coupling_joint',    'right_gripper_joint','right_gripper_finger_joint','right_gripper_left_outer_finger_joint',      'right_gripper_left_inner_finger_joint','right_gripper_left_inner_knuckle_joint',    'right_gripper_right_inner_knuckle_joint','right_gripper_right_outer_knuckle_joint',    'right_gripper_right_outer_finger_joint','right_gripper_right_inner_finger_joint']

       #open position
    pregrasp_posture : [0.0,0.0,0.0]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [1,1]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [0, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 0, 0] # 1.5707 = PI/2

    end_effector_parent_link: 'arm_left_link_tcp"'

